Local, Remote, and Relay Nodes.
decentralized-identity/decentralized-web-node pull request #225
Opened 2023-04-05 11:38 UTC by andorsk

Related to https://github.com/decentralized-identity/decentralized-web-node/issues/152

2023-04-05 23:02 UTC, TallTed requested changes
Tweaks for clarity

2023-04-05 23:02 UTC, TallTed commented on docs/companion_guide.md
> +
```suggestion
- **Relay:** A relay is a way for a remote node to forward information it receives to a
  local node, or to another remote node. When Jane sends a message to Bob's remote
  DWN, Bob's remote DWN "relays" the message to Bob's local DWN, which allows
  Bob to interact with his DWN locally.

```

2023-05-17 06:20 UTC, andorsk commented
Let's discuss over the DIF call today and see if this can be merged.

2023-05-17 06:25 UTC, andorsk commented
Thank you @TallTed for the tweaks! I've committed them. They look great.

2023-05-17 16:14 UTC, LiranCohen approved these changes

2023-05-17 16:14 UTC, merged