update service endpoint section
decentralized-identity/decentralized-web-node pull request #296
Opened 2024-04-03 14:59 UTC by LiranCohen

First pass at aligning the `Service Endpoints` sections.

When looking at this I found myself asking a question which I figured will be good to document here and talk on the call.

Does the `enc` or `sig` key have to reference a key that is associated with the resolved `DID`?

For example could the JSON example shown have `"sig": ["did:eample:bob#dwn-sig"]` ?

2024-04-03 15:13 UTC, csuwildcat commented
LMAO, I just did a PR for this too.

2024-04-03 16:23 UTC, andorsk commented
Note: do not follow beyond 1 levels deep recursion for `did` resolution.

2024-04-03 16:26 UTC, andorsk commented
@andorsk made a comment. TODO: add language around using service-profile for dwn spec.

2024-04-16 15:25 UTC, LiranCohen commented
Added the wording regarding recursion.

@andorsk Let's create a separate issue for the service-profile so that we can better define what properties can exist in the service profile. Could you also include a link to the service profile spec/docs in that issue?

2024-04-16 15:56 UTC, TallTed requested changes

2024-04-16 15:56 UTC, TallTed commented on spec/spec.md
> +  - an array of `string` values which each value represents a `URL` associated with a `DWN`
Is this really meant to be a MAY? Or is it meant as I've adjusted below?
```suggestion
- Service Endpoints ****MUST**** contain a `serviceEndpoint` property and it ****MUST**** be set to one of the following:
  - a `string` value which represents the `URL` associated with the `DWN`
  - an array of `string` values, each of which represents the `URL` associated with a `DWN`
```

2024-04-16 15:56 UTC, TallTed commented on spec/spec.md
> +- Service Endpoints ****MUST**** contain an `enc` property and it ****MUST**** be a `string` value or an array of `string` values which represent the `keyId` associated with `encrypting` data.
```suggestion
- Service Endpoints ****MUST**** contain an `enc` property which ****MUST**** be a `string` value or an array of `string` values, each of which represents a `keyId` associated with `encrypting` data.
```

2024-04-16 15:56 UTC, TallTed commented on spec/spec.md
> +- Service Endpoints ****MUST**** contain a `sig`property and it ****MUST**** be a `string` value or an array of `string` values which represent the `keyId` associated with `signing` data.
```suggestion
- Service Endpoints ****MUST**** contain a `sig` property which ****MUST**** be a `string` value or an array of `string` values, each of which represents a `keyId` associated with `signing` data.
```

2024-05-15 04:55 UTC, andorsk commented
Can we merge @TallTed 's updates and get this in?

2024-05-15 14:23 UTC, LiranCohen commented
Thank you @TallTed !! As always, excellent work!

2024-05-15 16:12 UTC, andorsk approved these changes
after TallTed's updates, I think this looks good to go.

2024-05-15 16:12 UTC, merged

2024-06-12 13:55 UTC, LiranCohen commented
Addresses: https://github.com/decentralized-identity/decentralized-web-node/issues/284